title: International Press journal CJJS author support
description: TeX related material for the manuscript preparation for the
             International Press journal Cambridge Journal for Junior Scientists
             (CJJS)
show_downloads: true
theme: jekyll-theme-tactile
